### ISSUE TITLE
is there new wrapper?

### ISSUE THREAD

**Issue by anoosi** [dead/libass.js#1]
hello,
is there one had made wrapper for libass.js
i use videojs and if i use another source not youtube the height and width change to original video sizes
thanks..

**Comment by dead** [comment]
Can you link me to a example?

**Comment by anoosi** [comment]
oh sorry to my bad english -_-
there is not one made wrapper !
but i just wonder if some one make it cuase the current wrapper in the example it's not good,
i realy need some one make it, until now i use https://github.com/Dador/JavascriptSubtitlesOctopus
but it without harfbuzz, so that mean not support rtl language and it's appear bad :(
thanks.

**Comment by dead** [comment]
Just updated the http://dead.github.io/libass.js/example-videojs/test-onecanvas.html
Try it again :) It should work now when the width/height changes.

**Comment by anoosi** [comment]
....

**Comment by anoosi** [comment]
oh now ok with videojs.libass-onecanvas.js
but when change to fullscreen the texts get blured unlikely  videojs.libass.js
![untitled](https://user-images.githubusercontent.com/14188374/31292782-5f15c450-aadd-11e7-9111-6acbb3224802.jpg)
do you can update videojs.libass.js or do something with onecanvas?
and what about dependency like libjass jquery long.js?
is there update coming  for that?
huge thanks..

**Comment by dead** [comment]
Now videojs.libass.js will work :)
I removed the long.js and jquery dependency. But the example still uses jquery only to show/hide the video/loading elements, you can change this to not use jquery if you want.

**Comment by anoosi** [comment]
now better than before, especially when you removed the dependencies.
thanks..
